version: 0.1

environment_variables:
  plaintext:
    MYSQL_USER: ubuntu
    MYSQL_PASSWORD:
    MYSQL_HOST: localhost
    MYSQL_TABLE: ci_test

phases:
  install:
    commands:
      - sudo apt-add-repository -y 'deb http://ppa.launchpad.net/ondrej/mysql-experimental/ubuntu precise main'
      - sudo apt-get update; sudo DEBIAN_FRONTEND=noninteractive apt-get install -y mysql-server-5.6
      - mysql -u ubuntu -e "CREATE DATABASE ci_test;"
      - bundle install
  pre_build:
    commands:
      - bundle exec rspec
