version: 0.1

environment_variables:
  plaintext:
    MYSQL_USER: root
    MYSQL_PASSWORD: hogehoge
    MYSQL_HOST: localhost
    MYSQL_TABLE: ci_test

phases:
  install:
    commands:
      - apt-get update
      - echo "mysql-server-5.6 mysql-server/root_password password ${MYSQL_PASSWORD}" | debconf-set-selections
      - echo "mysql-server-5.6 mysql-server/root_password_again password ${MYSQL_PASSWORD}" | debconf-set-selections
      - apt-get install -y mysql-server-5.6
      - service mysql start
      - mysql -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -e "CREATE DATABASE ${MYSQL_TABLE};"
      - bundle install
  pre_build:
    commands:
      - bundle exec rspec
