default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['MYSQL_USER'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host: <%= ENV['MYSQL_HOST'] %>

development:
  <<: *default
  database: <%= ENV['MYSQL_TABLE'] %>_development

test:
  <<: *default
  database: <%= ENV['MYSQL_TABLE'] %>_test

production:
  <<: *default
  database: <%= ENV['MYSQL_TABLE'] %>
